coqui:
  model: model.tflite
  scorer: large_vocabulary.scorer
  beam_width: 500
server:
  http:
    host: "0.0.0.0"
    port: 8080
    request_max_size: 33554432
log:
  level:
    - logger: deepspeech_server
      level: DEBUG